export const attributes = [
  {"id": 1, "abr": ".x", "nam": "taxon", "type": "text", "rep": "*", "ord": 11, "value": null},
  {"id": 2, "abr": ".p", "nam": "példány", "type": "tel", "rep": "*pd", "ord": 31, "value": null},
  {"id": 3, "abr": ".h", "nam": "hím", "type": "tel", "rep": "*h", "ord": 32, "value": null},
  {"id": 4, "abr": ".n", "nam": "nőstény", "type": "tel", "rep": "*n", "ord": 33, "value": null},
  {"id": 5, "abr": ".a", "nam": "adult", "type": "tel", "rep": "*ad", "ord": 34, "value": null},
  {"id": 6, "abr": ".j", "nam": "juvenilis", "type": "tel", "rep": "*juv", "ord": 35, "value": null},
  {"id": 7, "abr": "sub", "nam": "subadult", "type": "tel", "rep": "*sub", "ord": 36, "value": null},
  {"id": 8, "abr": "imm", "nam": "immature", "type": "tel", "rep": "*imm", "ord": 37, "value": null},
  {"id": 9, "abr": "pul", "nam": "pullus", "type": "tel", "rep": "*pull", "ord": 38, "value": null},
  {"id": 10, "abr": "tj", "nam": "tojás", "type": "tel", "rep": "* tojás", "ord": 39, "value": null},
  {"id": 11, "abr": "nh", "nam": "néhány pd", "type": "bool", "rep": null, "ord": 41, "value": null},
  {"id": 12, "abr": "tb", "nam": "több pd", "type": "bool", "rep": null, "ord": 42, "value": null},
  {"id": 13, "abr": "rk", "nam": "ritka", "type": "bool", "rep": null, "ord": 43, "value": null},
  {"id": 14, "abr": "sz", "nam": "szórványos", "type": "bool", "rep": null, "ord": 44, "value": null},
  {"id": 15, "abr": "gy", "nam": "gyakori", "type": "bool", "rep": null, "ord": 45, "value": null},
  {"id": 16, "abr": "tm", "nam": "tömeges", "type": "bool", "rep": null, "ord": 46, "value": null},
  {"id": 17, "abr": "tbf", "nam": "többfelé", "type": "bool", "rep": null, "ord": 47, "value": null},
  {"id": 18, "abr": "mdf", "nam": "mindenfelé", "type": "bool", "rep": null, "ord": 48, "value": null},
  {"id": 19, "abr": "elf", "nam": "előfordul", "type": "bool", "rep": null, "ord": 49, "value": null},
  {"id": 20, "abr": "fsz", "nam": "fészek", "type": "bool", "rep": null, "ord": 51, "value": null},
  {"id": 28, "abr": "nym", "nam": "nyom", "type": "bool", "rep": null, "ord": 51, "value": null},
  {"id": 29, "abr": "flt", "nam": "folt", "type": "bool", "rep": null, "ord": 51, "value": null},
  {"id": 30, "abr": "dg", "nam": "dög", "type": "bool", "rep": null, "ord": 51, "value": null},
  {"id": 31, "abr": "kcs", "nam": "közös csapatban", "type": "bool", "rep": null, "ord": 51, "value": null},
  {"id": 32, "abr": "tbc", "nam": "több csapatban", "type": "bool", "rep": null, "ord": 51, "value": null},
  {"id": 33, "abr": "ir", "nam": "irány", "type": "text", "rep": "*-felé", "ord": 51, "value": null},
  {"id": 34, "abr": "en", "nam": "ének", "type": "bool", "rep": null, "ord": 61, "value": null},
  {"id": 35, "abr": "hg", "nam": "hang", "type": "bool", "rep": null, "ord": 61, "value": null},
  {"id": 36, "abr": "chg", "nam": "csak hang", "type": "bool", "rep": null, "ord": 61, "value": null},
  {"id": 37, "abr": "ri", "nam": "riaszt", "type": "bool", "rep": null, "ord": 61, "value": null},
  {"id": 38, "abr": "at", "nam": "átrepülő", "type": "bool", "rep": null, "ord": 61, "value": null},
  {"id": 39, "abr": "vr", "nam": "virágzik", "type": "bool", "rep": null, "ord": 61, "value": null},
  {"id": 40, "abr": "ell", "nam": "ellenőrizendő", "type": "bool", "rep": null, "ord": 71, "value": null},
  {"id": 41, "abr": "kt", "nam": "kétes", "type": "bool", "rep": null, "ord": 71, "value": null},
  {"id": 42, "abr": "ft", "nam": "fotó", "type": "bool", "rep": null, "ord": 71, "value": null},
  {"id": 43, "abr": "fh", "nam": "fotóról határozva", "type": "bool", "rep": null, "ord": 71, "value": null},
  {"id": 44, "abr": "idp", "nam": "időpont", "type": "time", "rep": "időpont: *", "ord": 71, "value": null},
  {"id": 45, "abr": "kez", "nam": "kezdés", "type": "time", "rep": "kezdés: *", "ord": 71, "value": null},
  {"id": 46, "abr": "bef", "nam": "befejezés", "type": "time", "rep": "befejezés: *", "ord": 71, "value": null},
  {"id": 47, "abr": "bir", "nam": "birding.hu", "type": "tel", "rep": "birding.hu/*", "ord": 81, "value": null},
  {"id": 48, "abr": "ize", "nam": "izeltlabuak.hu", "type": "tel", "rep": "izeltlabuak.hu/*", "ord": 81, "value": null},
  {"id": 49, "abr": "hdb", "nam": "herbárium doboz", "type": "tel", "rep": "*hdb", "ord": 81, "value": null},
  {"id": 50, "abr": "hno", "nam": "herbárium szám", "type": "tel", "rep": "*hno", "ord": 81, "value": null}
]

export const observers = [
  {id: 1, nam: "Ócsag Attila"},
  {id: 2, nam: "Zsoldos Csaba"},
  {id: 3, nam: "Szalai Kornél"},
  {id: 4, nam: "Lendvai Csaba"},
  {id: 5, nam: "Bajor Zoltán"},
  {id: 6, nam: "Bodor István"},
  {id: 7, nam: "Szőke Gábor"},
  {id: 8, nam: "Novák Gábor"},
  {id: 9, nam: "Egyéb megfigyelők"}
]